version: '1'
models:
  haiku:
    provider: anthropic
    model: claude-3-5-haiku-latest
    description: Fast, cheap model for quick tasks
  sonnet:
    provider: anthropic
    model: claude-sonnet-4-20250514
    description: Balanced model for coding tasks
  opus:
    provider: anthropic
    model: claude-opus-4-20250514
    description: Most capable for complex reasoning
  llama3:
    provider: ollama-native
    model: llama3.2
    description: Free local model
  coder:
    provider: ollama-native
    model: qwen3-coder:480b-cloud
    description: Cloud coder
  gpt-4o-mini:
    provider: openai
    model: gpt-4o-mini
    description: Fast, cheap OpenAI model
  gpt-4o:
    provider: openai
    model: gpt-4o
    description: Capable OpenAI model
  qwen3-lite:
    provider: ollama-native
    model: qwen3:8b
    description: qwen lite
tasks:
  fast:
    model: haiku
    description: Quick tasks (commits, summaries)
  code:
    model: coder
    description: Standard coding tasks
  complex:
    model: gpt-4o
    description: Architecture, debugging
  summarize:
    model: llama3
    description: Context summarization
  document:
    model: qwen3-lite
commands:
  commit:
    task: fast
  fix:
    task: complex
fallbacks:
  primary:
    - coder
    - qwen3-lite
    - sonnet
    - haiku
    - llama3
pipelines:
  smart-refactor:
    description: Analyze, plan, implement, review
    steps:
      - name: analyze
        model: gpt-4o-mini
        prompt: 'Analyze refactoring opportunities: {input}'
        output: analysis
      - name: plan
        model: gpt-4o
        prompt: 'Create refactoring plan based on: {analysis}'
        output: plan
      - name: implement
        model: gpt-4o
        prompt: 'Implement the plan: {plan}'
        output: implementation
      - name: review
        model: gpt-4o-mini
        prompt: 'Quick review: {implementation}'
        output: review
    result: |-
      {implementation}

      ## Review
      {review}
