version: '1'

# Model definitions - map friendly names to provider/model pairs
models:
  haiku:
    provider: anthropic
    model: claude-3-5-haiku-latest
    description: Fast, cheap model for quick tasks
  sonnet:
    provider: anthropic
    model: claude-sonnet-4-20250514
    description: Balanced model for coding tasks
  opus:
    provider: anthropic
    model: claude-opus-4-5-20251101
    description: Most capable for complex reasoning (default)
  gpt-5:
    provider: openai
    model: gpt-5
    description: Latest GPT-5 model
  gpt-5-nano:
    provider: openai
    model: gpt-5-nano
    description: Fast, budget-friendly GPT-5
  gpt-4o:
    provider: openai
    model: gpt-4o
    description: Fast, capable GPT-4 model
  glm:
    provider: ollama
    model: glm-4.7:cloud
    description: Default Ollama model
  coder:
    provider: ollama
    model: qwen3-coder:480b-cloud
    description: default coder

# Task routing - map task types to models
tasks:
  fast:
    model: gpt-5-nano
    description: Quick tasks (commits, summaries)
  code:
    model: coder
    description: Standard coding tasks
  complex:
    model: glm
    description: Architecture, debugging
  summarize:
    model: glm
    description: Context summarization (local)

# Command routing - override task for specific commands
commands:
  commit:
    task: fast
  fix:
    task: complex

# Fallback chains - try models in order if one fails
fallbacks:
  primary:
    - opus
    - sonnet
    - haiku
    - gpt-5
    - glm

# Model roles - abstract roles for provider-agnostic pipelines
# Use with: /pipeline --provider anthropic <pipeline-name>
model-roles:
  fast:
    anthropic: haiku
    openai: gpt-5-nano
    ollama: glm
  capable:
    anthropic: sonnet
    openai: gpt-5
    ollama: glm
  reasoning:
    anthropic: opus
    openai: gpt-5
    ollama: glm

# Example pipeline using roles (provider-agnostic)
pipelines:
  code-review:
    description: Multi-step code review
    provider: anthropic
    steps:
      - name: quick-scan
        role: fast
        prompt: 'Quick scan for obvious issues: {input}'
        output: quick_issues
      - name: deep-analysis
        role: reasoning
        prompt: 'Deep analysis of code quality: {input}\n\nQuick scan found: {quick_issues}'
        output: analysis
      - name: suggestions
        role: capable
        prompt: 'Summarize actionable suggestions from: {analysis}'
        output: suggestions
    result: |-
      ## Code Review

      ### Quick Scan
      {quick_issues}

      ### Analysis
      {analysis}

      ### Suggestions
      {suggestions}
