version: '1'

# Model definitions - map friendly names to provider/model pairs
models:
  haiku:
    provider: anthropic
    model: claude-3-5-haiku-latest
    description: Fast, cheap model for quick tasks
  sonnet:
    provider: anthropic
    model: claude-sonnet-4-20250514
    description: Balanced model for coding tasks
  opus:
    provider: anthropic
    model: claude-opus-4-20250514
    description: Most capable for complex reasoning
  gpt-4o:
    provider: openai
    model: gpt-4o
    description: Fast, capable GPT-4 model
  gpt-4o-mini:
    provider: openai
    model: gpt-4o-mini
    description: Budget-friendly GPT-4
  llama3:
    provider: ollama
    model: llama3.2
    description: Free local model

# Task routing - map task types to models
tasks:
  fast:
    model: haiku
    description: Quick tasks (commits, summaries)
  code:
    model: sonnet
    description: Standard coding tasks
  complex:
    model: opus
    description: Architecture, debugging
  summarize:
    model: llama3
    description: Context summarization (free)

# Command routing - override task for specific commands
commands:
  commit:
    task: fast
  fix:
    task: complex

# Fallback chains - try models in order if one fails
fallbacks:
  primary:
    - sonnet
    - haiku
    - gpt-4o
    - llama3

# Model roles - abstract roles for provider-agnostic pipelines
# Use with: /pipeline --provider anthropic <pipeline-name>
model-roles:
  fast:
    anthropic: haiku
    openai: gpt-4o-mini
    ollama: llama3
  capable:
    anthropic: sonnet
    openai: gpt-4o
    ollama: llama3
  reasoning:
    anthropic: opus
    openai: gpt-4o
    ollama: llama3

# Example pipeline using roles (provider-agnostic)
pipelines:
  code-review:
    description: Multi-step code review
    provider: anthropic
    steps:
      - name: quick-scan
        role: fast
        prompt: 'Quick scan for obvious issues: {input}'
        output: quick_issues
      - name: deep-analysis
        role: reasoning
        prompt: 'Deep analysis of code quality: {input}\n\nQuick scan found: {quick_issues}'
        output: analysis
      - name: suggestions
        role: capable
        prompt: 'Summarize actionable suggestions from: {analysis}'
        output: suggestions
    result: |-
      ## Code Review

      ### Quick Scan
      {quick_issues}

      ### Analysis
      {analysis}

      ### Suggestions
      {suggestions}
